# Generated by Django 5.1.5 on 2025-01-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="public/documents/"
            ),
        ),
    ]
